apiVersion: v1
kind: Namespace
metadata:
  name: vernemq
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vernemq
  namespace: vernemq
spec:
  chart:
    git: https://github.com/Arsenikki/kuberseeni.git
    path: vernemq
  values:
    replicaCount: 2
    image:
      repository: timbrand/vernemq-rpi
      tag: 1.10.2