apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-hdd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/hdd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-hdd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3000Gi
---