replicaCount: 1

image:
  repository: haugene/transmission-openvpn
  tag: latest-armhf # Suffixed by -armhf to pull the ARM image
  pullPolicy: IfNotPresent

env:
  - name: OPENVPN_PROVIDER
    value: "PIA" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
  - name: OPENVPN_USERNAME
    valueFrom: # Reference to the secret | openvpn.username
      secretKeyRef:
        name: openvpn
        key: username
  - name: OPENVPN_PASSWORD
    valueFrom: # Reference to the secret | openvpn.password
      secretKeyRef:
        name: openvpn
        key: password
  - name: LOCAL_NETWORK
    value: "192.168.0.0/24"
  - name: TRANSMISSION_PEER_PORT
    value: "47444"
  - name: TRANSMISSION_DOWNLOAD_DIR
    value: /downloads/transmission
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

volumes:
  - name: media-hdd
    persistentVolumeClaim:
      claimName: media-hdd # PersistentVolumeClaim created earlier
  - name: dev-tun # Needed for VPN
    hostPath:
      path: /dev/net/tun

volumeMounts:
  - name: media-hdd
    mountPath: /data
    subPath: configs/transmission-data # Path /mnt/hdd/configs/transmission-data where transmission writes the configuration
  - name: media-hdd
    mountPath: /downloads/transmission
    subPath: downloads/transmission # Path /mnt/hdd/downloads/transmission where transmission downloads Torrents
  - name: dev-tun
    mountPath: /dev/net/tun # Needed for VPN

securityContext:
  capabilities: # Needed for VPN
    add:
      - NET_ADMIN